export default{
   items:[
      {
         name:"Expense",
         url:"/dashboard/expense",
         icon:"icon-tag"
      },
      {
         name:"Setting",
         url:"/dashboard/setting",
         icon:"icon-settings"
      },
      {
         name:"Profile",
         url:"/dashboard/profile",
         icon:"icon-user"
      }
   ]
}